name: Publish Python 🐍 distributions 📦 to TestPyPI
on:
  release:
    types: [published]
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.3"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Export requirements
        run: poetry version patch
      - name: Add token onfig
        run: poetry config pypi-token.pypi ${{ secrets.PROD_PYPI_TOKEN }}
      - name: Build
        run: poetry build 
      - name: Publish
        run: poetry publish
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}